In [1]:
import numpy as np
import pprint
np.set_printoptions(precision=5)
pp = pprint.PrettyPrinter(indent=4)

In [2]:
P = np.array([[0, 0.3, 0.7, 0],
[0.5, 0, 0.5, 0],
[0, 0.5, 0, 0.5],
[0, 0, 0.5, 0.5]])

In [4]:
for i in range(501):
    pp.pprint(np.linalg.matrix_power(P, i))
    print("."*50)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
..................................................
array([[0. , 0.3, 0.7, 0. ],
       [0.5, 0. , 0.5, 0. ],
       [0. , 0.5, 0. , 0.5],
       [0. , 0. , 0.5, 0.5]])
..................................................
array([[0.15, 0.35, 0.15, 0.35],
       [0.  , 0.4 , 0.35, 0.25],
       [0.25, 0.  , 0.5 , 0.25],
       [0.  , 0.25, 0.25, 0.5 ]])
..................................................
array([[0.175, 0.12 , 0.455, 0.25 ],
       [0.2  , 0.175, 0.325, 0.3  ],
       [0.   , 0.325, 0.3  , 0.375],
       [0.125, 0.125, 0.375, 0.375]])
..................................................
array([[0.06  , 0.28  , 0.3075, 0.3525],
       [0.0875, 0.2225, 0.3775, 0.3125],
       [0.1625, 0.15  , 0.35  , 0.3375],
       [0.0625, 0.225 , 0.3375, 0.375 ]])
..................................................
array([[0.14   , 0.17175, 0.35825, 0.33   ],
       [0.11125, 0.215  , 0.32875, 

Цепи Маркова с дискретным временем